import { NgModule } from '@angular/core';
import {
  MatSelectModule,
  MatAutocompleteModule,
  MatButtonModule,
  MatInputModule,
  MatCheckboxModule,
  MatRadioModule,
  MatTooltipModule,
  MatSlideToggleModule,
  MatGridListModule,
  MatCardModule,
  MatTabsModule,
  MatToolbarModule,
  MatListModule,
  MatMenuModule,
  MatIconModule,
  MatDialogModule,
  MatSidenavModule,
  MatTableModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatSnackBarModule, MatExpansionModule, MatFormFieldModule
} from '@angular/material';
import { CommonModule } from '@angular/common';
import { CdkTableModule } from '@angular/cdk/table';
import { FormsModule } from '@angular/forms';

@NgModule({
  imports: [
    MatProgressBarModule,
    MatSnackBarModule,
    CommonModule,
    CdkTableModule,
    MatTableModule,
    MatDialogModule,
    MatSnackBarModule,
    MatIconModule,
    MatMenuModule,
    MatListModule,
    MatToolbarModule,
    MatTabsModule,
    MatCardModule,
    MatGridListModule,
    MatTooltipModule,
    MatInputModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatButtonModule,
    MatRadioModule,
    MatCheckboxModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    FormsModule,
  ],
  exports: [
    MatFormFieldModule,
    MatProgressBarModule,
    MatExpansionModule,
    CommonModule,
    CdkTableModule,
    MatTableModule,
    MatDialogModule,
    MatSnackBarModule,
    MatIconModule,
    MatMenuModule,
    MatListModule,
    MatToolbarModule,
    MatTabsModule,
    MatCardModule,
    MatGridListModule,
    MatSlideToggleModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatRadioModule,
    MatInputModule,
    MatAutocompleteModule,
    MatSelectModule,
    MatButtonModule,
    MatSidenavModule,
    // DialogComponent,
    MatProgressSpinnerModule,
  ],
  // entryComponents: [DialogComponent],
})
export class AngularMaterialModule {
}
